export enum textJustifications {
  LEFT_JUSTIFY = 0,
  RIGHT_JUSTIFY = 1,
  CENTER_JUSTIFY = 2,
  FULL_JUSTIFY_LASTLINE_LEFT = 3,
  FULL_JUSTIFY_LASTLINE_RIGHT = 4,
  FULL_JUSTIFY_LASTLINE_CENTER = 5,
  FULL_JUSTIFY_LASTLINE_FULL = 6,
}
